---
operator: 5HmxV7yUHQnJYnVZVqDW2zd2qGznrvtqKLgyzFKnCS7jCAtT
chain: "https://mainnet-dev.deeper.network/rpc"
topic: ff68b5ae1c6eef082af114f218b96313f8eaa0e0ccbf5a4d2795eab86b5fdec4
wallet_dir: /var/web3d
wallet_filename: eth_key
eth_key_password: "9527"
