#!groovy

def slackChannel = '#deeper-machine'
def execNode = 'master-runner'
def ansiblePath = '/root/ansible/watcher-install/'
def upstreamProjects = ''

if (env.BRANCH_NAME == "master") {
    deployCmd = ""
}


pipeline {
    agent {
        node { label execNode }
    }

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '3'))
    }

    triggers {
        upstream(
            upstreamProjects: upstreamProjects,
            threshold: hudson.model.Result.SUCCESS
        )
    }
    environment {
        webhook_key = credentials('webhook_key')
        ANSIBLE_PATH = "${ansiblePath}"
    }

    stages {
        stage('test') {
            when {
                not {
                    anyOf {
                        branch 'master'
                    }
                }
            }
            stages {
                stage('Unit Test') {
                    steps {
                        echo 'prepare to code test'
                    //TODO
                    }
                }
                stage('report') {
                    when {
                        not {
                            branch 'PR-*'
                        }
                    }
                    steps {
                        echo 'generate code report'
                    //TODO
                    }
                }
            }
        }

        stage('Build') {
            when {
                anyOf {
                   branch env.BRANCH_NAME
                }
            }
            steps {               
                sh '''
                export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
                export CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
                export AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar
                export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
                cargo build --target=aarch64-unknown-linux-gnu --release
                    '''
            }
        }

        stage('Deploy code') {
            when {
                anyOf {
                    branch env.BRANCH_NAME
                }
            }
            steps {
                sh 'cp target/aarch64-unknown-linux-gnu/release/watcher $ANSIBLE_PATH/script'
                sh 'ansible-playbook -i $ANSIBLE_PATH/hosts $ANSIBLE_PATH/playbooks/watcher_install.yml'
            }
        }
    }
    post {
        success {
            slackSend channel: slackChannel, color: 'good',
                message: "${env.JOB_NAME} CICD SUCCESS,<${env.BUILD_URL}console|cliek me get details>"
        }
        failure {
            slackSend channel: slackChannel, color: 'danger',
                message: "${env.JOB_NAME} CICD FAILED!!! <${env.BUILD_URL}console|cliek me check log>"
        }
    }

}